name: Test code, build Containers for Production, push to Dockerhub.

on:
  push:
    branches:
      - main
      - develop

jobs:
  test-back: #job1
    name: Backend Test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup
        run: npm install

      - name: Run tests
        run: npm run test

  build-and-deploy-back: #job2
    runs-on: ubuntu-latest
    needs: test-back
    if: github.ref == 'refs/heads/main'
    name: Build and Deploy Back
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push Docker image
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/YOUR-CONTAINER-NAME:latest,${{ secrets.DOCKER_USERNAME }}/YOUR-CONTAINER-NAME:${{ github.sha }}